import * as THREE from './vendor/three.module.js';
const $=id=>document.getElementById(id),canvas=$("game");
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.1,120),world=new THREE.Group();scene.add(world);scene.background=new THREE.Color(0xa8c8da);scene.fog=new THREE.Fog(0xa8c8da,35,78);
scene.add(new THREE.HemisphereLight(0xffffff,0x56634b,2.2));const sun=new THREE.DirectionalLight(0xfff3d0,2.5);sun.position.set(15,25,8);sun.castShadow=true;scene.add(sun);
const COLOR_CAPER_WS_URL='wss://my-deployed-server.com';
let ws,id,state,me,selected='#fff',painting=false,lastSend=0,lastMap='',yaw=Math.PI,pitch=.2,lastPaint=0;const keys={},avatars=new Map(),colliders=[],raycaster=new THREE.Raycaster(),cameraRay=new THREE.Raycaster(),tracers=[];
const maps={farm:{floor:0x7eaa58,wall:0xc78d50,colors:['#7eaa58','#c78d50','#994c36','#e8ca68','#4e7142']},school:{floor:0xb7ad91,wall:0xe0d7ba,colors:['#b7ad91','#e0d7ba','#2c6b8b','#b4473f','#48515a']},library:{floor:0x704a34,wall:0xcbae82,colors:['#704a34','#cbae82','#315d48','#8b3636','#d5b660']},museum:{floor:0xb8b4ab,wall:0xe9e5d9,colors:['#b8b4ab','#e9e5d9','#4d6681','#8e6950','#252a30']}};
function box(x,y,z,w,h,d,color,solid=true){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.78}));o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;world.add(o);if(solid)colliders.push(new THREE.Box3().setFromObject(o));return o}
function cylinder(x,y,z,r,h,color){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,12),new THREE.MeshStandardMaterial({color}));o.position.set(x,y,z);o.castShadow=true;world.add(o);colliders.push(new THREE.Box3().setFromObject(o));return o}
function buildMap(name){world.clear();colliders.length=0;const m=maps[name];box(0,-.3,0,40,.6,28,m.floor,false);box(0,11.3,0,40,.5,28,0xf1ead8,false);box(0,5.5,-14,40,11,.5,m.wall);box(0,5.5,14,40,11,.5,m.wall);box(-20,5.5,0,.5,11,28,m.wall);box(20,5.5,0,.5,11,28,m.wall);box(0,-.3,19.5,10,.6,11,0x68747c,false);box(0,11.3,19.5,10,.5,11,0x596b78,false);box(0,4,25,10,8,.5,0x596b78);box(-5,4,19.5,.5,8,11,0x596b78);box(5,4,19.5,.5,8,11,0x596b78);
 if(name==='farm'){for(let i=0;i<18;i++)box(-16+(i%6)*6,1,(Math.floor(i/6)-1)*7,2.5,2,2.5,i%2?0xd9b65d:0xa96835);for(let i=0;i<8;i++){cylinder(-17+i*5,2.2,-11+(i%3)*11,.6,4.4,0x5a4931);const c=new THREE.Mesh(new THREE.SphereGeometry(2.2,10,8),new THREE.MeshStandardMaterial({color:0x527841}));c.position.set(-17+i*5,5,-11+(i%3)*11);world.add(c)}}
 if(name==='school'){for(let r=0;r<4;r++)for(let c=0;c<7;c++){box(-15+c*5,.75,-9+r*5,2.2,1.5,1.2,0x8b6847);box(-15+c*5,.6,-7.7+r*5,1.4,1.2,1.2,0x345d76)}for(let i=0;i<9;i++)box(-18+i*4.5,2.2,12,4,4.4,.8,i%2?0x3d6c85:0xb74c42)}
 if(name==='library'){for(let r=0;r<4;r++)for(let c=0;c<5;c++){const x=-16+c*8,z=-10+r*7;box(x,3,z,5,6,1,0x5e3928);for(let s=0;s<4;s++)box(x,1+s*1.35,z-.55,4.5,.15,.2,0xd0b067,false)}for(let i=0;i<5;i++)box(-12+i*6,1.1,3,4,2.2,2.4,0x784d32)}
 if(name==='museum'){for(let i=0;i<14;i++){const x=-16+(i%7)*5.3,z=-9+Math.floor(i/7)*18;box(x,.65,z,3,1.3,3,0x557080);const shape=new THREE.Mesh(i%2?new THREE.TorusKnotGeometry(.6,.18,48,8):new THREE.IcosahedronGeometry(.8),new THREE.MeshStandardMaterial({color:i%3?0xb48a5d:0x44505c}));shape.position.set(x,2,z);world.add(shape)}for(let i=0;i<4;i++)box(-12+i*8,.55,0,5,1.1,1.6,0x755d4c)}
 for(let x=-16;x<=16;x+=8)for(let z=-10;z<=10;z+=10){const light=new THREE.PointLight(0xfff3d0,8,12);light.position.set(x,9.8,z);world.add(light);box(x,10.9,z,3,.1,1.1,0xfff5cf,false)}}
function paintedMaterial(){const surface=document.createElement('canvas');surface.width=surface.height=256;const context=surface.getContext('2d');context.fillStyle='#fff';context.fillRect(0,0,256,256);const texture=new THREE.CanvasTexture(surface);texture.colorSpace=THREE.SRGBColorSpace;const material=new THREE.MeshStandardMaterial({map:texture,roughness:.68});return{surface,context,texture,material}}
function person(p){const g=new THREE.Group(),add=(geo,x,y,z)=>{const paint=paintedMaterial(),o=new THREE.Mesh(geo,paint.material);o.position.set(x,y,z);o.castShadow=true;o.userData.paint=paint;o.userData.part=g.children.length;g.add(o);return o};add(new THREE.SphereGeometry(.35,16,12),0,2.25,0);add(new THREE.BoxGeometry(.65,1.25,.35),0,1.35,0);add(new THREE.BoxGeometry(1.65,.25,.3),0,1.7,0);add(new THREE.BoxGeometry(.25,1.1,.3),-.2,.4,0);add(new THREE.BoxGeometry(.25,1.1,.3),.2,.4,0);g.userData.parts=g.children;g.userData.id=p.id;g.userData.paintSignature='';scene.add(g);return g}
function applyPaint(g,strokes=[]){const signature=JSON.stringify(strokes);if(signature===g.userData.paintSignature)return;g.userData.paintSignature=signature;for(const part of g.userData.parts){const p=part.userData.paint;p.context.fillStyle='#fff';p.context.fillRect(0,0,256,256)}for(const stroke of strokes){if(stroke.part==null||!g.userData.parts[stroke.part])continue;const p=g.userData.parts[stroke.part].userData.paint;p.context.fillStyle=stroke.c;p.context.beginPath();p.context.arc(stroke.u*256,(1-stroke.v)*256,stroke.r*2.2,0,Math.PI*2);p.context.fill()}g.userData.parts.forEach(part=>part.userData.paint.texture.needsUpdate=true)}
function sync(){if(!state)return;for(const p of state.players){let g=avatars.get(p.id);if(!g){g=person(p);avatars.set(p.id,g)}g.scale.setScalar(p.role==='seeker'?1:.25);g.position.lerp(new THREE.Vector3(p.x,p.y,p.z),p.id===id?1:.35);g.rotation.y=p.angle||0;g.visible=!p.tagged;applyPaint(g,p.paint)}for(const[pid,g]of avatars)if(!state.players.some(p=>p.id===pid)){scene.remove(g);avatars.delete(pid)}}
function collides(pos,scale){const r=.38*scale,h=2.8*scale,b=new THREE.Box3(new THREE.Vector3(pos.x-r,pos.y,pos.z-r),new THREE.Vector3(pos.x+r,pos.y+h,pos.z+r));return colliders.some(c=>c.intersectsBox(b))}
function move(dt,t){if(!me||state.phase==='lobby'||me.tagged)return;const f=(keys.w||keys.arrowup?1:0)-(keys.s||keys.arrowdown?1:0),s=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),v=(keys[' ']?1:0)-(keys.shift?1:0),forward=new THREE.Vector3(Math.sin(yaw),0,Math.cos(yaw)),right=new THREE.Vector3(-forward.z,0,forward.x),m=forward.multiplyScalar(f).add(right.multiplyScalar(s));if(m.lengthSq())m.normalize();m.y=v;const scale=me.role==='seeker'?1:.25,next=new THREE.Vector3(me.x,me.y,me.z).addScaledVector(m,(me.role==='seeker'?5:6)*dt);next.x=THREE.MathUtils.clamp(next.x,-19,19);next.z=THREE.MathUtils.clamp(next.z,-13,24);next.y=THREE.MathUtils.clamp(next.y,.05,10.4-scale*2.8);if(!collides(next,scale)){me.x=next.x;me.y=next.y;me.z=next.z}if(Math.abs(f)+Math.abs(s)>0)me.angle=Math.atan2(m.x,m.z);if(t-lastSend>45){ws.send(JSON.stringify({type:'move',x:me.x,y:me.y,z:me.z,angle:me.angle}));lastSend=t}}
function follow(){if(!me)return;const target=new THREE.Vector3(me.x,me.y+(me.role==='seeker'?1.5:.5),me.z),d=me.role==='seeker'?6:3,offset=new THREE.Vector3(-Math.sin(yaw)*Math.cos(pitch)*d,Math.sin(pitch)*d+1,-Math.cos(yaw)*Math.cos(pitch)*d),desired=target.clone().add(offset),direction=desired.clone().sub(target),distance=direction.length();cameraRay.set(target,direction.normalize());cameraRay.far=distance;const hit=cameraRay.intersectObjects(world.children,true)[0];if(hit)desired.copy(target).addScaledVector(direction,Math.max(.7,hit.distance-.35));camera.position.lerp(desired,.2);camera.lookAt(target)}
function connect(type){if(COLOR_CAPER_WS_URL.includes('my-deployed-server.com')){alert('Set COLOR_CAPER_WS_URL in script.js to your deployed backend WSS URL first.');return}ws=new WebSocket(COLOR_CAPER_WS_URL);ws.onopen=()=>ws.send(JSON.stringify({type,name:$("name").value||'Player',code:$("code").value}));ws.onmessage=e=>handle(JSON.parse(e.data));ws.onerror=()=>alert('Could not connect to the Color Caper server. Check the WSS URL and backend deployment.');ws.onclose=()=>{if(!state)alert('Disconnected from the Color Caper server.')}}
function handle(m){if(m.type==='welcome')id=m.id;if(m.type==='state'){state=m;me=state.players.find(p=>p.id===id);if(lastMap!==m.map){lastMap=m.map;selected=maps[m.map].colors[0];buildMap(m.map)}$("menu").classList.add('hidden');$("roomLabel").textContent=`ROOM ${m.code}`;$("roomCode").textContent=m.code;$("players").textContent=m.players.map(p=>p.name).join(' · ');$("lobby").style.display=m.phase==='lobby'?'block':'none';$("paint").style.display=me&&me.role==='hider'&&m.phase==='hide'?'block':'none';palette()}if(m.type==='error')alert(m.message)}
function shoot(){if(!me||me.role!=='seeker'||state.phase!=='hunt')return;raycaster.setFromCamera(new THREE.Vector2(),camera);const targets=[...avatars.values()].filter(g=>g.userData.id!==id),hits=raycaster.intersectObjects([...world.children,...targets],true);let target=null,end=camera.position.clone().add(raycaster.ray.direction.clone().multiplyScalar(45));if(hits.length){end.copy(hits[0].point);let g=hits[0].object;while(g.parent&&!g.userData.id)g=g.parent;if(g.userData.id)target=g.userData.id}const material=new THREE.LineBasicMaterial({color:target?0xfff09b:0xff9f66,transparent:true,opacity:1}),geometry=new THREE.BufferGeometry().setFromPoints([camera.position.clone(),end]),line=new THREE.Line(geometry,material);scene.add(line);tracers.push({line,life:.22});ws.send(JSON.stringify({type:'shoot',target}))}
$("create").onclick=()=>connect('create');$("join").onclick=()=>connect('join');$("start").onclick=()=>ws.send(JSON.stringify({type:'start'}));$("map").onchange=e=>ws.send(JSON.stringify({type:'settings',map:e.target.value}));
function paintAt(e){if(!painting||!me||performance.now()-lastPaint<22)return;lastPaint=performance.now();const own=avatars.get(id);if(!own)return;const rect=canvas.getBoundingClientRect(),pointer=new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-((e.clientY-rect.top)/rect.height)*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObject(own,true)[0];if(!hit||!hit.uv)return;const stroke={part:hit.object.userData.part,u:hit.uv.x,v:hit.uv.y,r:+$("brush").value,c:selected};me.paint=me.paint||[];me.paint.push(stroke);if(me.paint.length>80)me.paint.shift();applyPaint(own,me.paint);ws.send(JSON.stringify({type:'paint',stroke}))}
function palette(){if(!state)return;$("palette").innerHTML=maps[state.map].colors.map(c=>`<button class="swatch ${selected===c?'active':''}" style="background:${c}" data-c="${c}"></button>`).join('');document.querySelectorAll('.swatch').forEach(b=>b.onclick=()=>{selected=b.dataset.c;palette()})}
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);canvas.addEventListener('mousemove',e=>{if(painting){paintAt(e);return}const viewWidth=Math.max(1,canvas.getBoundingClientRect().width);yaw-=e.movementX*(Math.PI*2/viewWidth);pitch=THREE.MathUtils.clamp(pitch+e.movementY*(Math.PI/viewWidth),-.55,1.05)});canvas.addEventListener('pointerdown',e=>{if(me&&me.role==='hider'&&state.phase==='hide'){painting=true;lastPaint=0;canvas.setPointerCapture(e.pointerId);paintAt(e)}else shoot()});canvas.addEventListener('pointerup',e=>{painting=false;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId)});canvas.addEventListener('pointercancel',()=>painting=false);
function loop(t){requestAnimationFrame(loop);const dt=Math.min(.04,(t-(loop.last||t))/1000);loop.last=t;move(dt,t);sync();follow();for(let i=tracers.length-1;i>=0;i--){const shot=tracers[i];shot.life-=dt;shot.line.material.opacity=Math.max(0,shot.life/.22);if(shot.life<=0){scene.remove(shot.line);shot.line.geometry.dispose();shot.line.material.dispose();tracers.splice(i,1)}}renderer.render(scene,camera);if(state&&me){$("phase").textContent=`${state.phase.toUpperCase()} · ${me.role.toUpperCase()}`;const r=state.ends?Math.max(0,Math.ceil(state.ends-Date.now()/1000)):0;$("timer").textContent=r?`${r}s`:'--';$("notice").textContent=state.phase==='hide'?(me.role==='seeker'?'WAITING ROOM · Hiders are painting':'DRAG DIRECTLY ON YOUR 3D AVATAR'):state.phase==='hunt'?(me.tagged?'YOU WERE TAGGED':'THE SEEKER IS LOOSE'):state.phase==='results'?'ROUND OVER':'WAITING FOR PLAYERS'}}function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();buildMap('farm');requestAnimationFrame(loop);
